import AppKit
@preconcurrency import ApplicationServices
import Carbon.HIToolbox
import Foundation
import UniformTypeIdentifiers

@MainActor
final class ClipboardService {
    private let pasteboard = NSPasteboard.general
    private var lastChangeCount = NSPasteboard.general.changeCount
    private var timer: Timer?
    var onItem: ((Clip) -> Void)?
    var settings: AppSettings?

    func start() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.45, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.readIfChanged() }
        }
    }
    func stop() { timer?.invalidate() }

    private func readIfChanged() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount
        let frontmost = NSWorkspace.shared.frontmostApplication
        if let bundleID = frontmost?.bundleIdentifier,
           settings?.ignoredApps.contains(where: { $0.bundleID == bundleID }) == true {
            return
        }
        guard var item = makeItem() else { return }
        item.sourceApplication = frontmost?.localizedName
        item.sourceApplicationBundleID = frontmost?.bundleIdentifier
        // 创建时即计算并持久化来源 app 主色调，避免渲染时重复计算
        if let bundleID = frontmost?.bundleIdentifier {
            item.sourceAppColor = AppIconCache.shared.codableDominantColor(forBundleID: bundleID)
        }
        // 自动检测色值文本 → 重分类为 .colorValue
        if item.kind == .text && item.isColorValue {
            item.kind = .color
        }
        onItem?(item)
    }

    // MARK: - 内容颜色提取

    /// 从复制的文本和富文本数据中提取内容颜色：
    /// 1. 颜色值文本（#RGB / #RRGGBB / #RRGGBBAA）
    /// 2. 富文本（RTF/RTFD）中的背景色
    private func extractContentColor(text: String?, allData: [UTIEntry]) -> CodableColor? {
        // 1. 色值文本
        if let t = text?.trimmingCharacters(in: .whitespacesAndNewlines) {
            if t.hasPrefix("#") && [4, 7, 9].contains(t.count) {
                var hexStr = String(t.dropFirst())
                if hexStr.count == 3 {
                    let chars = Array(hexStr)
                    hexStr = "\(chars[0])\(chars[0])\(chars[1])\(chars[1])\(chars[2])\(chars[2])"
                }
                if hexStr.count == 6, let v = UInt64(hexStr, radix: 16) {
                    return CodableColor(
                        red: Double((v >> 16) & 0xFF) / 255,
                        green: Double((v >> 8) & 0xFF) / 255,
                        blue: Double(v & 0xFF) / 255
                    )
                }
            }
        }
        // 2. 富文本背景色
        for entry in allData {
            guard entry.uti == "public.rtf" || entry.uti == "com.apple.flat-rtfd" else { continue }
            if let attr = try? NSAttributedString(
                data: entry.data,
                options: [.documentType: NSAttributedString.DocumentType.rtf],
                documentAttributes: nil
            ), attr.length > 0,
               let bgColor = attr.attribute(.backgroundColor, at: 0, effectiveRange: nil) as? NSColor,
               let rgb = bgColor.usingColorSpace(.sRGB) {
                return CodableColor(
                    red: Double(rgb.redComponent),
                    green: Double(rgb.greenComponent),
                    blue: Double(rgb.blueComponent)
                )
            }
        }
        return nil
    }

    private func makeItem() -> Clip? {
        let allTypes = pasteboard.types ?? []
        
        // 1. 检测安全标记：遇到 ConcealedType / TransientType / AutoGeneratedType 时跳过
        if ClipboardService.hasSecurityMarker(allTypes) {
            return nil
        }
        
        // 2. 过滤掉所有 org.nspasteboard.* 标记类型，只保留真实内容类型
        let availableTypes = ClipboardService.filteredTypes(allTypes)
        
        // 先收集所有 UTI 及其数据，供所有 kind 使用
        var allData: [UTIEntry] = []
        for t in availableTypes {
            if let data = pasteboard.data(forType: t), !data.isEmpty {
                allData.append(UTIEntry(uti: t.rawValue, data: data))
            }
        }
        let allPasteboardData = allData.isEmpty ? nil : allData
        let contentColor = extractContentColor(
            text: pasteboard.string(forType: .string),
            allData: allData
        )
        
        // 选取首选 UTI（按优先级）
        let primaryUTI = preferredUTI(from: availableTypes)
        let primaryUTIData = primaryUTI.flatMap { pasteboard.data(forType: NSPasteboard.PasteboardType($0)) }
        
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL], !urls.isEmpty {
            return Clip(kind: .file, fileURLs: urls, uti: primaryUTI, utiData: primaryUTIData, allPasteboardData: allPasteboardData, contentColor: contentColor)
        }
        if let url = pasteboard.readObjects(forClasses: [NSURL.self], options: nil)?.first as? URL, url.scheme != "file" {
            return Clip(kind: .link, url: url, uti: primaryUTI, utiData: primaryUTIData, allPasteboardData: allPasteboardData, contentColor: contentColor)
        }
        if let image = NSImage(pasteboard: pasteboard), let tiff = image.tiffRepresentation, tiff.count < 12_000_000 {
            // 优先采用 allPasteboardData 中的**原始图片格式**数据（png/jpeg/heic/webp…），
            // 仅当缺失时才回退 TIFF，避免统一转 TIFF 丢失原始格式信息并增大体积。
            let originalImageData = allPasteboardData?
                .first { $0.uti != "public.tiff" && (UTType($0.uti)?.conforms(to: .image) ?? false) }?
                .data
                ?? tiff
            return Clip(kind: .image, imageData: originalImageData, uti: primaryUTI, utiData: primaryUTIData, allPasteboardData: allPasteboardData, contentColor: contentColor)
        }
        if let text = pasteboard.string(forType: .string), !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            let kind: ClipKind = text.hasPrefix("http://") || text.hasPrefix("https://") ? .link : .text
            return Clip(kind: kind, text: text, url: URL(string: text), uti: primaryUTI, utiData: primaryUTIData, allPasteboardData: allPasteboardData, contentColor: contentColor)
        }
        
        // 兜底：如果前面所有分支都没匹配到（例如某些 app 只写了自定义 UTI），
        // 但只要 allPasteboardData 有数据，就根据类型创建合适的 Clip
        if let allPasteboardData = allPasteboardData, !allPasteboardData.isEmpty {
            // 检查是否有图片类型（PNG/TIFF/SVG/WebP 等）
            let imageUTIKeys = ["public.png", "public.tiff", "com.microsoft.bmp", "public.jpeg",
                                "public.svg-image", "public.webp", "org.ink.image"]
            let hasImageData = allPasteboardData.contains { entry in
                imageUTIKeys.contains(entry.uti) || entry.data.count > 100
            }
            
            // 检查是否有 URL
            var extractedURL: URL?
            for entry in allPasteboardData {
                if let text = String(data: entry.data, encoding: .utf8), let url = URL(string: text) {
                    extractedURL = url
                    break
                }
            }
            
            // 检查是否有纯文本
            let extractedText = pasteboard.string(forType: .string)
            
            if hasImageData {
                // 优先用原始图片格式（非 TIFF），回退 TIFF
                let imageData = allPasteboardData.first { $0.uti != "public.tiff" && (UTType($0.uti)?.conforms(to: .image) ?? false) }?.data
                    ?? allPasteboardData.first(where: { $0.uti == "public.tiff" })?.data
                return Clip(kind: .image, imageData: imageData, uti: primaryUTI, utiData: primaryUTIData, allPasteboardData: allPasteboardData, contentColor: contentColor)
            } else if let url = extractedURL {
                return Clip(kind: .link, url: url, uti: primaryUTI, utiData: primaryUTIData, allPasteboardData: allPasteboardData, contentColor: contentColor)
            } else if let text = extractedText, !text.isEmpty {
                return Clip(kind: .text, text: text, uti: primaryUTI, utiData: primaryUTIData, allPasteboardData: allPasteboardData, contentColor: contentColor)
            } else {
                // 最后兜底：创建一个 link 类型，保存所有原始数据
                return Clip(kind: .link, text: extractedText, url: extractedURL, uti: primaryUTI, utiData: primaryUTIData, allPasteboardData: allPasteboardData, contentColor: contentColor)
            }
        }
        
        return nil
    }

    // MARK: - UTI 优先级选择

    /// 从 pasteboard.types 中挑选最有意义的 UTI。
    ///
    /// 采用 **UTI 一致性判断（`conforms(to:)`）** 而非字符串精确匹配，
    /// 因此能正确识别 `public.heic` / `public.webp` / `dyn.*` 等未列入硬编码列表的类型。
    /// 类别优先级（从最「富」到最「贫」）：
    /// RTF > HTML > 纯文本 > 图片 > 文件 > URL > 第一个可用类型。
    private func preferredUTI(from types: [NSPasteboard.PasteboardType]) -> String? {
        let candidates = ClipboardService.filteredTypes(types)
        guard !candidates.isEmpty else { return nil }

        // 解析为 UTType；无法解析的（如遗留 NSStringPboardType）交给兜底处理。
        let utTypes = candidates.compactMap { UTType($0.rawValue) }

        // 每个类别内取粘贴板声明顺序中的第一个命中项，保证「最具体优先」。
        let categoryPriority: [UTType] = [.rtf, .html, .plainText, .image, .fileURL, .url]
        for category in categoryPriority {
            if let match = utTypes.first(where: { $0.conforms(to: category) }) {
                return match.identifier
            }
        }
        return candidates.first?.rawValue
    }

    func copy(_ item: Clip, plainText: Bool = false) {
        let plain = plainText || (settings?.alwaysPastePlainText ?? false)
        pasteboard.clearContents()
        if plain {
            switch item.kind {
            case .text: pasteboard.setString(item.text ?? "", forType: .string)
            case .link: pasteboard.setString(item.url?.absoluteString ?? item.text ?? "", forType: .string)
            case .file: pasteboard.setString((item.fileURLs ?? []).map(\.path).joined(separator: "\n"), forType: .string)
            case .image:
                if let data = item.imageData, let image = NSImage(data: data) { pasteboard.writeObjects([image]) }
            case .color: pasteboard.setString(item.text ?? "", forType: .string)
            }
        } else {
            // 优先使用保存的所有 UTI 数据写回，完整还原来源格式
            if let allPasteboardData = item.allPasteboardData, !allPasteboardData.isEmpty {
                // 按优先级排序写入：RTF > HTML > utf8-plain-text > plain-text > 其他
                let orderedKeys = [
                    "public.rtf", "com.apple.flat-rtfd", "public.html",
                    "public.utf8-plain-text", "public.plain-text",
                    "public.png", "public.tiff", "public.jpeg",
                    "public.file-url", "public.url"
                ]
                var orderedEntries = [UTIEntry]()
                for key in orderedKeys {
                    if let entry = allPasteboardData.first(where: { $0.uti == key }) {
                        orderedEntries.append(entry)
                    }
                }
                // 追加其他不在 orderedKeys 中的类型
                for entry in allPasteboardData where !orderedEntries.contains(where: { $0.uti == entry.uti }) {
                    orderedEntries.append(entry)
                }
                for entry in orderedEntries {
                    // 写回时再次排除安全标记，防止旧数据中残留 org.nspasteboard.* 类型
                    if !entry.uti.hasPrefix("org.nspasteboard.") {
                        pasteboard.setData(entry.data, forType: NSPasteboard.PasteboardType(entry.uti))
                    }
                }
            } else if let uti = item.uti, let utiData = item.utiData {
                pasteboard.setData(utiData, forType: NSPasteboard.PasteboardType(uti))
            }
            // 兜底 fallback（无 allPasteboardData/uti 的旧数据）
            if item.allPasteboardData == nil && item.uti == nil {
                switch item.kind {
                case .text: pasteboard.setString(item.text ?? "", forType: .string)
                case .link: pasteboard.setString(item.url?.absoluteString ?? item.text ?? "", forType: .string)
                case .image:
                    if let data = item.imageData, let image = NSImage(data: data) { pasteboard.writeObjects([image]) }
                case .file: pasteboard.writeObjects((item.fileURLs ?? []).map { $0 as NSURL })
                case .color: pasteboard.setString(item.text ?? "", forType: .string)
                }
            }
        }
        lastChangeCount = pasteboard.changeCount
    }

    // MARK: - Pasteboard security markers

    /// Universal pasteboard marker types that signal sensitive, transient, or
    /// auto-generated content.  Well-behaved clipboard managers filter these out
    /// so they never leak into history.
    ///
    /// - `ConcealedType` — confidential / password data (should be skipped entirely)
    /// - `TransientType` — temporary content that will be replaced within seconds
    /// - `AutoGeneratedType` — programmatically inserted; user had no copy intent
    private static let securityMarkerTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    /// Returns true when **any** of the given types is a security marker.
    private static func hasSecurityMarker(_ types: [NSPasteboard.PasteboardType]) -> Bool {
        types.contains { securityMarkerTypes.contains($0.rawValue) }
    }

    /// Filter out only the three known security-marker types, keeping everything
    /// else (including org.nspasteboard.source which carries source app info).
    private static func filteredTypes(_ types: [NSPasteboard.PasteboardType]) -> [NSPasteboard.PasteboardType] {
        types.filter { !securityMarkerTypes.contains($0.rawValue) }
    }
    func paste(_ item: Clip, plainText: Bool = false) {
        copy(item, plainText: plainText)
        guard ensureAccessibilityPermission() else { return }
        let ownPID = ProcessInfo.processInfo.processIdentifier
        let frontmost = NSWorkspace.shared.frontmostApplication
        let target: NSRunningApplication?
        if let frontmost, frontmost.processIdentifier != ownPID {
            target = frontmost
        } else {
            target = AppDelegate.invokingApplication
        }
        performPaste(into: target)
    }

    private func ensureAccessibilityPermission() -> Bool {
        if AXIsProcessTrusted() { return true }
        
        // 弹出系统原生辅助功能授权对话框，用户确认后会自动将 App 加入 Accessibility 列表
        let options = [kAXTrustedCheckOptionPrompt.takeUnretainedValue() as String: true] as CFDictionary
        AXIsProcessTrustedWithOptions(options)
        
        return AXIsProcessTrusted()
    }

    private func performPaste(into target: NSRunningApplication?) {
        // 不再调用 NSApp.hide — 面板由 PanelController 在粘贴前同步 orderOut。
        // 此时 app 未激活（非激活面板），目标 app 仍是前台。
        if let target, !target.isTerminated {
            target.activate(options: [.activateAllWindows])
        }
        waitForTargetFocus(target, attempts: 0)
    }

    /// 轮询直到目标 app 真正前台 **且本 app 不再持有 key window**（面板已消失），
    /// 再发送 ⌘V。否则面板仍是 key window，按键会被面板吞掉。
    private func waitForTargetFocus(_ target: NSRunningApplication?, attempts: Int) {
        let ownPID = ProcessInfo.processInfo.processIdentifier
        let frontmostPID = NSWorkspace.shared.frontmostApplication?.processIdentifier
        let targetIsFrontmost = target.map { frontmostPID == $0.processIdentifier } ?? (frontmostPID != nil && frontmostPID != ownPID)
        let weAreNotKey = NSApp.keyWindow == nil
        if (targetIsFrontmost && weAreNotKey) || attempts >= 25 {
            postPasteKeystroke()
            return
        }
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.04) { [weak self] in
            self?.waitForTargetFocus(target, attempts: attempts + 1)
        }
    }

    /// Post ⌘V through the HID event tap so it is indistinguishable from a real
    /// keystroke. `postToPid` bypasses the HID layer and is ignored by many apps.
    private func postPasteKeystroke() {
        let source = CGEventSource(stateID: .hidSystemState)
        let keyCode = CGKeyCode(kVK_ANSI_V)
        let down = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: true)
        let up = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: false)
        down?.flags = .maskCommand
        up?.flags = .maskCommand
        down?.post(tap: .cghidEventTap)
        up?.post(tap: .cghidEventTap)
        guard let settings, settings.soundEnabled, !settings.soundName.isEmpty else { return }
        NSSound(named: NSSound.Name(settings.soundName))?.play()
    }
}
